const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info: {
        version: "1.0.0",
        title: "Project 2 API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "l06-personal-assignment.onrender.com",
    schemes: ['https']
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./routes/index.js']

swaggerAutogen(outputFile, endpointsFiles, doc);