// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/64858a5999dedd5bb8616839
###
GET http://localhost:8080/contacts/64858a8d99dedd5bb861683a
###
GET http://localhost:8080/contacts/64858aa299dedd5bb861683b

// PRODUCTION Deploy
###
GET https://personal-assignment-2.onrender.com/contacts
###
GET https://personal-assignment-2.onrender.com/contacts/64858a5999dedd5bb8616839
###
GET https://personal-assignment-2.onrender.com/contacts/64858a8d99dedd5bb861683a
###
GET https://personal-assignment-2.onrender.com/contacts/64858aa299dedd5bb861683b